runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.app

libraries:
- name: MySQLdb
  version: "latest"

env_variables:
  
  CLOUDSQL_CONNECTION_NAME: landgrab-151015:europe-west1:landgrab
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: donut
  CLOUDSQL_DB: landgrab_db
  GRID_TABLE: grid_squares
  USER_TABLE: users

  LAT_SCALE: 0.000180
  LNG_SCALE: 0.000288

  MAX_LEVEL: 3