runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.app

libraries:
- name: MySQLdb
  version: "latest"

env_variables:
  
  CLOUDSQL_CONNECTION_NAME: landgrab-151015:europe-west1:landgrab
  CLOUDSQL_IP: 146.148.27.235
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: donut
  CLOUDSQL_DB: landgrab_db
  GRID_TABLE: grid_squares
  USER_TABLE: users
  USER_ITEMS_TABLE: user_items
  ACCESS_TOKEN_TABLE: accessTokens

  LAT_SCALE: 0.000270
  LNG_SCALE: 0.000432

  MAX_STACK: 2

  TEAMS: red,green,blue

  ITEMS: d

  FACEBOOK_APP_ID: 772280542937420
  FACEBOOK_APP_SECRET: 6e5f68c251907d0a121a242bd421f520

  
