runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.app

libraries:
- name: MySQLdb
  version: "latest"

env_variables:
  
  CLOUDSQL_CONNECTION_NAME: mysql:unix_socket=/cloudsql/landgrab-151015:europe-west1:landgrab;dbname=LandGrab_DB
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: donut

  LAT_SCALE: 0.000180
  LONG_SCALE: 0.000288